export interface QrCodeDetails {
  qrUrl: string;
  expiresAt: string;
  downloadUrl: string;
}

export interface QrVerificationResult {
  valid: boolean;
  prescriptionId?: number;
  error?: string;
}

export const qrCodeService = {
  /**
   * Generates a unique QR code URL, expiration timestamp, and download endpoint.
   * By default, the link is valid for 24 hours.
   */
  generateQrCodeDetails: (prescriptionId: number, durationHours: number = 24): QrCodeDetails => {
    // Generate a unique token for the QR link
    const uniqueToken = `qr_${Math.random().toString(36).substring(2, 11)}_${Date.now()}`;
    
    // Configurable duration (default 24 hours) converted to milliseconds
    const expiresMs = Date.now() + durationHours * 60 * 60 * 1000;
    
    // Construct the absolute download landing page URL
    const origin = typeof window !== "undefined" ? window.location.origin : "http://localhost:3000";
    const qrUrl = `${origin}/prescription/download?id=${prescriptionId}&token=${uniqueToken}&expires=${expiresMs}`;
    
    // Mock backend download API endpoint
    const downloadUrl = `/api/prescription/download/${prescriptionId}`;

    return {
      qrUrl,
      expiresAt: new Date(expiresMs).toISOString(),
      downloadUrl,
    };
  },

  /**
   * Verifies the authenticity and expiration of a scanned QR code token.
   */
  verifyQrCode: async (
    prescriptionId: number,
    token: string,
    expiresMs: number
  ): Promise<QrVerificationResult> => {
    // Simulate API latency
    await new Promise((resolve) => setTimeout(resolve, 600));

    if (!token || !prescriptionId || isNaN(expiresMs)) {
      return {
        valid: false,
        error: "Invalid QR code parameter sequence. The download link is malformed.",
      };
    }

    const now = Date.now();
    if (now > expiresMs) {
      return {
        valid: false,
        prescriptionId,
        error: "This QR code has expired. Please contact your doctor to obtain a new QR code.",
      };
    }

    return {
      valid: true,
      prescriptionId,
    };
  },

  /**
   * Downloads the prescription PDF file as a blob.
   * This matches the future backend download API contract.
   */
  downloadPrescriptionPdf: async (prescriptionId: number): Promise<Blob> => {
    // Simulate network delay for fetching the PDF
    await new Promise((resolve) => setTimeout(resolve, 800));

    // Construct a mock PDF document structure to download
    const mockPdfContent = 
`%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R >>
endobj
4 0 obj
<< /Length 120 >>
stream
BT
/F1 12 Tf
72 712 Td
(ANTSS CLINICAL PORTAL - PRESCRIPTION DOWNLOAD) Tj
0 -20 Td
(Prescription ID: ${prescriptionId}) Tj
0 -20 Td
(This digital copy is verified and generated by the ANTSS EMR platform.) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000056 00000 n 
0000000111 00000 n 
0000000200 00000 n 
trailer
<< /Size 5 /Root 1 0 R >>
startxref
370
%%EOF`;

    // Convert the mock PDF text format to a real Blob object
    return new Blob([mockPdfContent], { type: "application/pdf" });
  },

  /**
   * Utility to trigger the browser's download prompt for a Blob file
   */
  triggerBlobDownload: (blob: Blob, fileName: string): void => {
    if (typeof window === "undefined") return;
    
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }
};
